### ISSUE TITLE
eks-tester pulling in kubernetes/kubernetes makes the main module hard to depend on

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kubetest2#10]
kubetest2 is going to be a very difficult dependency to work with when the EKS provider pulls in kubernetes/kubernetes at a particular version. https://github.com/kubernetes/test-infra/pull/17869#issuecomment-667255485

one way or another this should be removed from the main module, which should NOT depend on kubernetes/kubernetes

/assign @amwat

**Comment by amwat** [comment]
/cc @gyuho 

yeah i think i'm planning on making each deployer it's own submodule.

**Comment by BenTheElder** [comment]
I think this may make versioning and `go get` problematic, but depending on k/k is unnaceptable, that's a dependency management nightmare for anyone else trying to work with this.

**Comment by gyuho** [comment]
@BenTheElder We do not want to block the migration. While we are cleaning up the dependency (probably we will package everything in binary, and call it as subprocess), please feel free to remove eks provider.

**Comment by BenTheElder** [comment]
thanks @gyuho :pray: 

I think:
> While we are cleaning up the dependency (probably we will package everything in binary, and call it as subprocess)

sounds like a good approach :+1:
