### ISSUE TITLE
testsuite name does not show up in spyglass JUnit lens

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kubetest2#107]
The testsuite names shows up in testgrid https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

but not in the spyglass lens
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1368978837181829120

/cc @chizhg @spiffxp 

xref: kubernetes/enhancements#2464, https://github.com/kubernetes/test-infra/pull/21180#issuecomment-793063005 ,

**Comment by chizhg** [comment]
Hmm I saw they are shown on the spyglass lens (if you expand the passed tests and scroll down to the very bottom):
![image](https://user-images.githubusercontent.com/19399934/110388157-804c0180-8017-11eb-97d7-8ee829907247.png)

**Comment by amwat** [comment]
yeah, that should look like

```
kubetest2: Build
kubetest2: Up
kubetest2: Test
kubetest2: Down
```

**Comment by chizhg** [comment]
Got it, thanks!
I've made the fix in https://github.com/kubernetes-sigs/kubetest2/pull/105 since they are kinda related.

**Comment by amwat** [comment]
verified I see it correctly in spyglass now

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1369115504463056896
