### ISSUE TITLE
Add a version command

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kubetest2#108]
`kubetest2 --version` should output the tag/commit that it's built from.

This is especially important since currently kubetest2 is used in a lot of place by go getting (mostly latest)
so knowing which exact binary(commit) was used is useful. 
This will be further useful if it gets surfaced in testgrid metadata for any kubetest2 based job.

Additionally, this should be done for all the in-tree deployers and testers.

The version will also reflect the release once we move to tagged releases.
related: https://github.com/kubernetes-sigs/kubetest2/issues/17

A typical useful pattern is to inject and set package variables at build time through linker flags.
https://blog.alexellis.io/inject-build-time-vars-golang/

A good example can be found in the kind repo

https://github.com/kubernetes-sigs/kind/blob/fbf6cdcf5240c6b994657c9a4f85657ee0591331/Makefile#L57

https://github.com/kubernetes-sigs/kind/blob/fbf6cdcf5240c6b994657c9a4f85657ee0591331/pkg/cmd/kind/version/version.go

xref: https://github.com/kubernetes/enhancements/issues/2464

/help
/good-first-issue

**Comment by amwat** [comment]
/remove-help
Please ping with any questions if you need help :)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kubetest2/pull/111 is in but needs follow-ups (I think)

**Comment by coryrc** [comment]
`since currently kubetest2 is used in a lot of place by go getting`

I don't believe there's any way the callee (kubetest2 repo) to inject the version when something uses `go install`.

**Comment by BenTheElder** [comment]
> I don't believe there's any way the callee (kubetest2 repo) can inject the version when something uses go install.

we have a version when you call kind even with `go get`. the solution is to have a placeholder hardcoded value and then sometimes override those symbols.

https://github.com/kubernetes-sigs/kind/blob/e0f885dbd565cf6449aa806e5093440db69d002d/pkg/cmd/kind/version/version.go#L1

https://github.com/kubernetes-sigs/kind/blob/c029e821c07b3c821ee3bde7b7386b8859d968ed/Makefile#L57

**Comment by coryrc** [comment]
Sure, with `go get` you get VersionCore-VersionPreRelease which certainly narrows it down, but this sentence cannot be fulfilled to my knowledge by the callee:

```
since currently kubetest2 is used in a lot of place by go getting (mostly latest)
so knowing which exact binary(commit) was used is useful.
```

The caller can (they could set that linker flag w/ go install, or they could use your makefile), but not the callee, right?

**Comment by BenTheElder** [comment]
Yes, I should have looked back at the rest of the context 💯  

With kind IMO we instead encourage:
- binaries from head are available to curl (which set this, and is cheaper/quicker/simpler than go-get anyhow)
- most people should use releases

IMO it's an anti-pattern that kubetest2 encourages go get at HEAD still, as soon as we tag a version `go get sigs.k8s.io/kubetset/...` will be a stable version which can have the version hard-coded, and we should also encourage using stable versions.

I think the problem has just been getting to a point ready to tag as a version, which seems to be getting overdue for at least v0.1.x

**Comment by amwat** [comment]
+1 yeah we should release a v0.1.0 soon.

For the record I don't think we "encourage" folks to go get it from HEAD :) that's just how I've seen most folks use it. /shrug
Definitely a stable tag and/or atleast a fixed commit is better. Pre-built curlable binaries (that would come with the release) would be the best.

We already have them for CI: https://gcsweb.k8s.io/gcs/k8s-staging-kubetest2/

@coryrc you can inject build time variables during `go get` as well

`go get -ldflags 'pathToVariable=$COMMIT' sigs.k8s.io/kubetest2@$COMMIT`

Agreed this is complicated for a human to do, but possible to setup in CI as part of getting the binary.
Anyway this issue is to have such functionality(injectable version) in the first place :)

**Comment by BenTheElder** [comment]
> For the record I don't think we "encourage" folks to go get it from HEAD :) that's just how I've seen most folks use it. /shrug

right now go get *is* got get from HEAD until there is a tagged version, encouraging `go get` is the same as encouraging this until we tag it.
