### ISSUE TITLE
[GKE/EXE] exe tester does not accept multiple arguments

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/kubetest2#113]
Hi all

I am getting an intermittent error running this

```bash
kubetest2 gke --cluster-name kubetest --project chris-love-operator-playground --zone us-central1-a --ignore-gcp-ssh-key --up --down --test=exec -- bazel test --stamp //e2e/... --test_arg=--pvc=true
```

The error is 

```
I0317 14:01:41.262479 1782430 request.go:655] Throttling request took 1.046899937s, request: GET:https://34.68.57.200/apis/apps/v1?timeout=32s
panic: failed to fetch preferred server resource: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

I am thinking that the GKE cluster is not up fully?

**Comment by chrislovecnm** [comment]
Using just the `--up` is working fine, but when I use `--up --down` it does not run the tests.

**Comment by amwat** [comment]
Can you share the entire log?
I don't think there's any parsing error from the command.

`request.go` seems to be something from the bazel test itself so it does seems to be executed correctly?

**Comment by amwat** [comment]
this seems like it was because of the cluster readiness, being discussed in https://github.com/kubernetes-sigs/kubetest2/issues/114

not an argument parsing issue

/close
