### ISSUE TITLE
EKS deployer

### ISSUE THREAD

**Issue by rutigs** [kubernetes-sigs/kubetest2#116]
Hey guys, is there any plan on supporting an EKS deployer? 

I looked at kubetest 1 in the past as a way test a standard runtime I put on my EKS clusters but have since not kept up with the project and just stumbled across this today.

**Comment by amwat** [comment]
Note: one of the main goals of kubetest2 is to support out-of-tree deployers (not implemented in this repository, but follow the kubetest2 conventions). 

I am somewhat aware of `kubetest2-eks` plans over at https://github.com/aws/aws-k8s-tester#aws-k8s-tester 
(might be a good place to start there?)

cc @gyuho 

/close
