### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/kubetest2#134]
There's no user documentation for kubetest2.  I had to dig through source code to see what environment variables are passed to the test.  Please add documentation for all environment variables that the test has available.

https://github.com/kubernetes-sigs/kubetest2/blob/master/pkg/app/app.go#L129

**Comment by amwat** [comment]
+1 , we lack documentation in general, there's some at https://github.com/kubernetes/community/blob/2bf70285c638872f0e1e8650ab6ce1df6a4ba25c/contributors/devel/sig-testing/e2e-tests-kubetest2.md#testing-against-an-existing-cluster

But a lot of aspects aren't covered there.

/kind documentation
/priority important-soon
/help
