### ISSUE TITLE
bug: `make quick-verify` fail on local test

### ISSUE THREAD

**Issue by Yiyiyimu** [kubernetes-sigs/kubetest2#138]
When try to test kubetest2 on kind and run `make quick-verify`, the problem come with
```
kubetest2 kind --up --down --test=exec -- kubectl get all -A
I0607 15:39:30.357663    6091 app.go:59] RunDir for this run: "/home/shuyang/go/src/sig.k8s.io/kubetest2/_artifacts/41593815-2b32-49b1-a611-7d59891e4d15"
I0607 15:39:30.358923    6091 app.go:90] ID for this run: "41593815-2b32-49b1-a611-7d59891e4d15"
I0607 15:39:30.358952    6091 up.go:62] Up(): creating kind cluster...
Creating cluster "" ...
ERROR: failed to create cluster: '' is not a valid cluster name, cluster names must match `^[a-zA-Z0-9_.-]+$`
I0607 15:39:30.439751    6091 down.go:32] Down(): deleting kind cluster...
Deleting cluster "" ...
Error: exit status 1
Makefile:82: recipe for target 'quick-verify' failed
make: *** [quick-verify] Error 1
```

Find from here, that somewhat kind name is set to empty
https://github.com/kubernetes-sigs/kubetest2/blob/1eb0d61beff534d941a25b1fce5e9041a77be7f3/kubetest2-kind/deployer/deployer.go#L49-L61

So I need to run `kubetest2 kind --up --cluster-name "name" --down --test=exec -- kubectl get all -A` to fix the problem.

**Comment by amwat** [comment]
Which kind version are you using? (Check using `kind version`)
IIRC KIND supports passing empty string and will default to use `kind` as the cluster name.

Can you also try running kind directly with `kind create cluster --name ""`?

**Comment by Yiyiyimu** [comment]
Sry forgot to leave kind version, it's `v0.8.1`. And using the latest version `v0.11.0` could fix this problem. Thanks for the prompt help!
