### ISSUE TITLE
Can we remove the hardcoded clusterloader2 folder name appended to $ARTIFACTS in --report-dir ?

### ISSUE THREAD

**Issue by piyushgupta1551** [kubernetes-sigs/kubetest2#151]
**Current situation -** 
- when a perf test is executed using `kubetest2-tester-clusterloader2` via a prow job, the results of the test are created in $artifacts/clusterloader2 which cannot be read by perfdash (perfdash looks for results inside the artifacts folder only)
- Upon reading further, it seems that the concatenation of clusterloader2 to $artifacts is hardcoded and cannot be bypassed in any way and `--report-dir` is not longer a valid argument for the clusterloader2 tester. 
Refer - https://github.com/kubernetes-sigs/kubetest2/blob/f4c453f4732bac11a186d89764024117f3860ec1/pkg/testers/clusterloader2/cl2.go#L81

**Why is this required?**
We are trying to execute these perf tests on ppc64le arch Cloud VMs and have perfdash read the test result data.
With the mandatory clusterloader2 folder being created inside the $arifatcs folder, perfdash is no longer able to read test data.

I understand this may have been done originally with a purpose but wanted to check if we can make this concatenation optional so that someone can bypass the clusterloader folder creation inside $ARTIFACTS folder if and when required?

Note: I could not find a way to bypass this but please let me know if there is any way to do so in the existing code.

**Comment by amwat** [comment]
I don't have any strong objections. IIRC I don't think there was a specific reason for it to be named under sub directory that way. That being said I'm not sure if anything should assume that all generated artifacts would be in the top-level directory in the first place. But if perfdash is expecting in such a way I think that's a sane default.

I think we should solve it by doing both i.e. change the default to be top-level $ARTIFACTS and also expose the flag on the `--report-dir` clusterloader2 tester.

/triage accepted
/priority important-soon

**Comment by piyushgupta1551** [comment]
Tx @amwat . Should I go ahead and raise the PR for these changes? Will remove the clusterloader2 folder name (make $ARTIFACTS folder as default) and will enable --report-dir as an arg to the tester.

**Comment by amwat** [comment]
That sounds great! Thank you
