### ISSUE TITLE
Add E2E tests for kubetest2 gke deployer

### ISSUE THREAD

**Issue by chizhg** [kubernetes-sigs/kubetest2#152]
Since there has been active development on kubetest2 gke deployer, which has been used by multiple projects, it'll be good if we can have some e2e test coverage for it.

**Comment by chizhg** [comment]
@amwat if there is a Boskos project pool that can be used, I would be happy to take this task.

**Comment by amwat** [comment]
big +1 I was planning on opening up this issue :) 

I think we can use the existing one https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/boskos-resources.yaml#L229

/priority critical-urgent
