### ISSUE TITLE
Documentation and Examples

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/kubetest2#16]
If these exist, please close this issue, but I am having a rough time finding documentation and examples.  This project looks AWESOME, but I would love to use it, and I am uncertain how to.  I have figured out that I can do this:

```bash
kubetest2 kind --up --down --test=exec -- kubectl get all -A
```

But what is the best pattern to use inside of a go unit test?  Is this the pattern?

```bash
kubetest2 kind --up
```
Run my test code. And then

```bash
kubetest2 kind --down
```

Rather than running it directly, should I vendor `kube2test` and use it programmatically?

Thanks in advance!

**Comment by pymander** [comment]
We have some examples and a getting started guide in the Developer Guide here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests-kubetest2.md

**Comment by BenTheElder** [comment]
In addition to the docs listed above, docs for this repo are now tracked in https://github.com/kubernetes-sigs/kubetest2/issues/134
