### ISSUE TITLE
--use-built-binaries for tests doesn't work with kind deployer

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/kubetest2#184]
Setting the `--use-built-binaries` flag for running tests doesn't seem to be working when using the kind deployer because the kind node image builder doesn't bundle the e2e.test binary. 

I wasn't sure if this was expected behavior but being able to run a single command to build a kind node image, start the cluster, and then run tests would be useful:
```
kubetest2 kind --build --test=ginkgo --up --kube-root=$(pwd) --config=./kind-config.yaml -- --focus-regex=<regex> --use-built-binaries
```

**Comment by BenTheElder** [comment]
That seems like a bug, the builder should build the e2e binary, similar to https://github.com/kubernetes-sigs/kind/blob/main/hack/ci/e2e-k8s.sh

/help

**Comment by aramase** [comment]
Hitting this issue in our job too: https://prow.k8s.io/log?container=test&id=1625285724066549760&job=pull-kubernetes-e2e-kind-kms. This is the command we're running: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-auth/sig-auth-encryption-at-rest.yaml#L41-L52

/remote-lifecycle stale

**Comment by elieser1101** [comment]
is this still needed?
