### ISSUE TITLE
Should binaries have there own repo or how do we manage deps better?

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/kubetest2#19]
I think we have an interesting problem here with dependencies.  I am wondering if we have binaries like say hypothetically `kubetest2-kops` in its own repo or hosted in the kops repo.  Dependencies are nontrial to manage with the k8s projects, which we already saw with us removing the kubetest2-eks.

Thoughts?

**Comment by amwat** [comment]
That is the intention :) Ideally you can implement your own deployer out of tree and still use the end-to-end flow as long as the deployers and tester are named correctly.

**Comment by BenTheElder** [comment]
imho kubetest2 should avoid taking on many dependencies in the core, after your PR it's pretty nice at:

https://github.com/kubernetes-sigs/kubetest2/blob/ef32b5b18e53c4a13ef35e95e8b7e60b10c72ec4/go.mod#L5-L12

If any of the in-tree sample deployers want non-trivial dependencies for their own use, we should probably make them pull that into a separate binary / module one way or another to avoid that polluting the core package.

I would hope that `kubestest2-kops` could e.g. shell out to `kops` and be in-tree without any additional dependencies, but if kops wants to import kops code inside `kubetest2-kops` then we should probably put it in the kops repo.
The shim / binary-plugin style mechanism is intended to make this viable.

**Comment by BenTheElder** [comment]
The answer for now is: they are in another repo. https://github.com/kubernetes/kops/tree/9dc910bdac92468793b4e4eff9b75524044291bd/tests/e2e/kubetest2-kops
