### ISSUE TITLE
Implement minikube deployer

### ISSUE THREAD

**Issue by tallclair** [kubernetes-sigs/kubetest2#190]
Would be great to have a minikube deployer, as an alternative to kind for local development.

/help

**Comment by BenTheElder** [comment]
FWIW: We don't necessarily intend to have all deployers in this repo, kubetest2 is usable as a library, we have a few `exec` based deployers here as references, but for example `kops` implements one in their repo, so they can use kops as a library (and not pollute the dependencies in this repo).

https://kops.sigs.k8s.io/contributing/testing/#kubernetes-e2e-testing
https://pkg.go.dev/k8s.io/kops/tests/e2e/kubetest2-kops

We had a lot of headache with kubetest as a single binary and deployer dependencies in the past, so kubetest2 is hopefully very easy to import, shim, and support in external projects.

There's an argument to be made for moving out the existing deployers, though we probably want to keep at least one of the no-dependency deployers just as a reference implementation.

We also have extremely little bandwidth to review and approve changes in this repo, currently I am the only active approver 🙃 , so implementing additional deployers externally keeps down my already over-subscribed review load.

**Comment by tallclair** [comment]
That makes sense. In that case, it might be helpful to keep an index of other deployer implementations here.
