### ISSUE TITLE
Is gsutil package required to run kubetest2?

### ISSUE THREAD

**Issue by pbxqdown** [kubernetes-sigs/kubetest2#239]
I'm running with `kind` deployer on my local machine(`KUBE_GIT_VERSION=v1.27.0 kubetest2 kind --up --test=ginkgo -- --focus-regex='\[Conformance\]'`) but get following error:
```
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
I0816 00:09:13.279804   12136 ginkgo.go:139] Using kubeconfig at /home/qian/.kube/config
F0816 00:09:13.280042   12136 ginkgo.go:255] failed to run ginkgo tester: failed to get ginkgo test package from published releases: failed to get latest release name: exec: "gsutil": executable file not found in $PATH
Error: exit status 255
```

Since kind is used for testing, I think kubetest2 shouldn't depend on any cloud-provider?

**Comment by dims** [comment]
@pbxqdown if you have `kubectl` in path, it will not try to get a fresh one from our published artifacts

**Comment by pbxqdown** [comment]
@dims thanks, is there a way to resolve the issue or doc to follow the process? In a k8s developer's environment `kubectl` is usually included.
