### ISSUE TITLE
How to narrow down target test cases

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes-sigs/kubetest2#257]
I am trying to make fixes in `kubelet` in a locally built kubernetes and I want to execute e2e tests for kubelet. 
I use `kind` to make local clusters and I have been considering using `kubetest2` using below command:

```
kubetest2-kind -v 2 --kube-root $GOPATH/src/k8s.io/kubernetes \
 --config cluster.yaml \
 --build \
 --up \
 --down \
 --test=ginkgo
```

But it takes over 7 hours, it's too long. 
So, is there any option to filter test cases(i.e. kubelet e2e tests only)?

Thank you.

**Comment by jbpratt** [comment]
hey @YuikoTakada , you can pass the `--focus-regex` and `--skip-regex` flags down like this:

https://github.com/kubernetes-sigs/kubetest2/blob/bcfe5d638d28a621254e53d159c04874694cbc0b/kubetest2-gce/ci-tests/buildupdown.sh#L60-L64

feel free to reopen this if you have an issues with it!

/close
