### ISSUE TITLE
Writing custom tests

### ISSUE THREAD

**Issue by legolego621** [kubernetes-sigs/kubetest2#258]
Hi, I'm new to kubetest2.
I'm planning to write tests for my cluster using kubetest2.
I noticed that kubetest2 has a ginkgo tester. Can I integrate my own tests written by ginkgo into it or I have to write own custom tester?

**Comment by GanjMonk** [comment]
All tests are paced in the k8s repo https://github.com/kubernetes/kubernetes/tree/master/test
tester just execute this tests

**Comment by legolego621** [comment]
thanks!
is it rigth way to run my custom ginkgo tests like?

```
kubetest2 deployer \
  ---
  ---
  --test=exec \
  -- ginkgo -v 
```
