### ISSUE TITLE
Should have a noop deployer

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kubetest2#45]
Currently kubetest2 requires a deployer entrypoint.
One common use case is to run tests on an existing cluster, for which the deployer is mostly a noop.
kubetest has something similar: https://github.com/kubernetes/test-infra/blob/master/kubetest/none.go

**Comment by amwat** [comment]
FYI @pymander

**Comment by randomvariable** [comment]
Interested in this as we're a potential consumer in Cluster API.

We've also inverted the deployer flow somewhat, where we have a test framework that deploys clusters using Cluster API and then runs kubetest.

**Comment by amwat** [comment]
the #sig-testing channel and meeting in the kubernetes slack is the best place (https://github.com/kubernetes-sigs/kubetest2#community-discussion-contribution-and-support)

Yup, definitely should consider a kubetest2 CAP* deployer (since that would solve the exact use case you described)

**Comment by randomvariable** [comment]
Thanks, will create a new issue for tracking.
