### ISSUE TITLE
Add Cluster API deployer

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/kubetest2#48]
Breaking out of #45 into a new issue

Creating a Cluster API deployer for kubetest would present a number of benefits:

* Being able to run kubetest across any Cluster API infrastructure implementation.
* Allows for minimal infrastructure specific code in this repo
* Expands testing possibilities (e.g. routable ipv6 in AWS)

At a high-level, the deployer would need to do things along the following lines:
* Start a kind cluster, or re-use one with a known good Kubernetes version
* Allow user of kubetest to pass in as input: Cluster API versions, infrastructure provider, cluster sizing, etc...
* Install Cluster API components
* Deploy cluster and wait
* Pass kubeconfig to kubetest to run

Cluster API currently has its own test framework, which is importable in library form to do e2e testing, bits of which can be leveraged for testing.

Cluster API providers such as that for AWS also additionally have an inverted workflow in order to run kubetest against main branches of Cluster API itself for conformance.

**Comment by benmoss** [comment]
started on this here https://github.com/benmoss/kubetest2/tree/capi-deployer

**Comment by randomvariable** [comment]
Maybe we should put the capi-deployer in the Cluster API repository under test/kubetest2-cluster-api in the first instance?

See https://github.com/kubernetes/kops/pull/10031 for the similar effort.

**Comment by benmoss** [comment]
Yeah I think while we're still iterating on it it's nice to have it somewhere we don't need to do PR's/code review each revision

**Comment by randomvariable** [comment]
Oh, absolutely, just mean, when you PR it, we should probably own it in CAPI.

**Comment by benmoss** [comment]
Opened a PR here https://github.com/kubernetes-sigs/cluster-api/pull/3855

**Comment by randomvariable** [comment]
Nice. Will take a look.

**Comment by amwat** [comment]
/remove-lifecycle rotten

I think this is being worked on out-of-tree (which is really great to see!)
https://github.com/kubernetes-sigs/cluster-api/pull/4041

/close
