### ISSUE TITLE
ginkgo - Support downloading kubernetes client tar

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/kubetest2#79]
Currently the gingko tester supports [downloading the e2e test package tar](https://github.com/kubernetes-sigs/kubetest2/blob/master/pkg/testers/ginkgo/package.go) from a GCS bucket to use a specific version of the test package.

For test runs in which k/k is not being built it would be useful to support the same functionality for the kubernetes client package. This way we can align kubectl + kubernetes + e2e.test versions.

I'm implementing a kubetest2 deployer for kops and noticed this discrepancy because the prow image our jobs use has a 1.20 kubectl in its PATH and a text change in 1.20 is [causing the 1.19 e2e tests to fail](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/10504/pull-kops-e2e-kubernetes-aws-kubetest2/1344672653306236928). The original kubetest downloaded kubectl via get-kube.sh and I think it would be useful to support similar functionality in kubetest2.

**Comment by amwat** [comment]
+1 this would be a great addition and will also preemptively solve version skew problems.

/priority important-soon
/help
