### ISSUE TITLE
Don't extract e2e.test and ginkgo binary into artifacts.BaseDir()

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/kubetest2#97]
These two binaries are extracted under the Artifacts folder and collected post-run and this end up utilizing a lot of space in the GCS which is not required as nothing else is captured, hence it will be good if we can put them into some temp folder and trigger from there

**Comment by mkumatag** [comment]
location: https://github.com/kubernetes-sigs/kubetest2/blob/a964c23a8ca7f8653ec446769d52ea6b598ff4d2/pkg/testers/ginkgo/package.go#L96-L97

**Comment by mkumatag** [comment]
> I could see both sides here, it might be useful for someone while debugging to know exactly what binary was used.
> But agree that it should be intentional, and configurable.
> 
> In general, we want to add a way where deployer/testers can choose to distinguish the artifacts used during the run vs the artifacts that the deployer/tests want to upload.

Agree for somecase it will be helpful to collect as artifacts but in case of downloading or using these binaries from some other repository is very costly, not everyone can afford that default feature. As you mentioned let's think about putting it somewhere else so that artifact does not collect it.

**Comment by amwat** [comment]
This is fairly similar to https://github.com/kubernetes-sigs/kubetest2/issues/98 let's track it there. 

Once that is fixed, default would be `RunDir()` (so no upload) and we can add functionality to allow optionally uploading (by copying them back to artifacts.BaseDir())

/cc @justinsb 

/close
