### ISSUE TITLE
Decouple RunDir from Artifacts

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kubetest2#98]
A tracking issue for: https://github.com/kubernetes-sigs/kubetest2/pull/91#pullrequestreview-591825637

RunDir: should be used for storing all files in general specific to a single run of kubetest2
Artifacts: should only be used intentionally for storing files which (in CI) get automatically uploaded to GCS. 

also helps with: https://github.com/kubernetes-sigs/kubetest2/issues/97

/cc @justinsb @mkumatag 

The logical separation was added in: https://github.com/kubernetes-sigs/kubetest2/pull/91
But currently RunDir (by default) is a subdirectory under artifacts, so there's no actual separation yet.

**Comment by Rajalakshmi-Girish** [comment]
@amwat I have started working on this. Below is the approach that I thought of. Can you please confirm if this seems good to proceed?

- Have RunDir out of Artifacts and decoupled as this issue aims. (Not a subdirectory. Default RunDir shall be `_rundir` at the same level as `_artifacts`)

- All the files related to a specific run(Binaries, metadata.json, junit_runner.xml and junit_*.xml files) would be initially be stored in RunDir.

- Later, the junit files would be copied to Artifacts directory once the run completes. (Copy of junit files from RunDir to Artifacts would happen unconditionally)

- A new flag `upload-test-binaries`  would be introduced that would be `False` by default. If this flag is passed `True` in the `kubetest2` command, the binaries (gingko, e2e.test, kubectl) would be copied to Artifacts from Rundir.
Else the binaries would be left only in Rundir and not be uploaded to storage.

**Comment by Rajalakshmi-Girish** [comment]
> @amwat I have started working on this. Below is the approach that I thought of. Can you please confirm if this seems good to proceed?
> 
>     * Have RunDir out of Artifacts and decoupled as this issue aims. (Not a subdirectory. Default RunDir shall be `_rundir` at the same level as `_artifacts`)
> 
>     * All the files related to a specific run(Binaries, metadata.json, junit_runner.xml and junit_*.xml files) would be initially be stored in RunDir.
> 
>     * Later, the junit files would be copied to Artifacts directory once the run completes. (Copy of junit files from RunDir to Artifacts would happen unconditionally)
> 
>     * A new flag `upload-test-binaries`  would be introduced that would be `False` by default. If this flag is passed `True` in the `kubetest2` command, the binaries (gingko, e2e.test, kubectl) would be copied to Artifacts from Rundir.
>       Else the binaries would be left only in Rundir and not be uploaded to storage.

@mkumatag your thoughts on above please.
