### ISSUE TITLE
[GCE] [Failing Test] conformance nodePort tests

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kubetest2#99]
https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

xref: https://github.com/kubernetes/enhancements/issues/2464

After moving to `config-test.sh` in https://github.com/kubernetes-sigs/kubetest2/pull/96 the default GCE network name changed from `default` to `e2e-test-${USER}`
so changes initially added in https://github.com/kubernetes-sigs/kubetest2/pull/34 are not taking effect.

/cc @BenTheElder @spiffxp

**Comment by BenTheElder** [comment]
and the gce network name breaks the test...? 😬

**Comment by amwat** [comment]
The tests need extra setup to open up the nodePort range which needs to know the name of the network, we were defaulting to the wrong one.
